<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="35" started-at="2018-01-11T13:43:59Z" finished-at="2018-01-11T13:43:59Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="35" started-at="2018-01-11T13:43:59Z" finished-at="2018-01-11T13:43:59Z">
      <class name="KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest">
        <test-method status="FAIL" signature="loadConfig(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest@7cd62f43]" name="loadConfig" is-config="true" duration-ms="0" started-at="2018-01-11T19:13:59Z" finished-at="2018-01-11T19:13:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.mysql.jdbc.Driver]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[jdbc:mysql://192.168.35.2:3391/NITIC]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[root]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[NITIC_Input_Quote]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[NITIC_Output_Quote]]>
              </value>
            </param>
          </params>
          <exception class="com.selenium.exception.DatabaseException">
            <message>
              <![CDATA[ERROR IN DB - URL / USERNAME / PASSWORD]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.selenium.exception.DatabaseException: ERROR IN DB - URL / USERNAME / PASSWORD
	at com.selenium.SupportingClasses.DatabaseOperation.ConnectionSetup(DatabaseOperation.java:74)
	at KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest.loadConfig(NITICCreateQuoteTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'NITIC'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.selenium.SupportingClasses.DatabaseOperation.ConnectionSetup(DatabaseOperation.java:70)
	... 20 more
]]>
            </full-stacktrace>
          </exception> <!-- com.selenium.exception.DatabaseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method status="SKIP" signature="setUp(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest@7cd62f43]" name="setUp" is-config="true" duration-ms="0" started-at="2018-01-11T19:13:59Z" finished-at="2018-01-11T19:13:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="Login(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest@7cd62f43]" name="Login" duration-ms="1" started-at="2018-01-11T19:13:59Z" finished-at="2018-01-11T19:13:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://niticqa.solartis.net/NITIC/NITIC/Login.xhtml]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[nitic_uw]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[welcome1]]>
              </value>
            </param>
          </params>
          <exception class="com.selenium.exception.DatabaseException">
            <message>
              <![CDATA[ERROR IN DB - URL / USERNAME / PASSWORD]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.selenium.exception.DatabaseException: ERROR IN DB - URL / USERNAME / PASSWORD
	at com.selenium.SupportingClasses.DatabaseOperation.ConnectionSetup(DatabaseOperation.java:74)
	at KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest.loadConfig(NITICCreateQuoteTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'NITIC'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.selenium.SupportingClasses.DatabaseOperation.ConnectionSetup(DatabaseOperation.java:70)
	... 20 more
]]>
            </full-stacktrace>
          </exception> <!-- com.selenium.exception.DatabaseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="SKIP" signature="createQuote(java.lang.Integer, java.lang.Object, java.lang.Object)[pri:0, instance:KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest@7cd62f43]" name="createQuote" duration-ms="0" started-at="2018-01-11T19:13:59Z" data-provider="UITestData" depends-on-methods="KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest.Login" finished-at="2018-01-11T19:13:59Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NITICCreateQuoteTest.createQuote(java.lang.Integer, java.lang.Object, java.lang.Object)[pri:0, instance:KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest@7cd62f43] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NITICCreateQuoteTest.createQuote(java.lang.Integer, java.lang.Object, java.lang.Object)[pri:0, instance:KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest@7cd62f43] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createQuote -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest@7cd62f43]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-01-11T19:13:59Z" finished-at="2018-01-11T19:13:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- KeywordDrivenFramework.KeywordDrivenFramework.NITICCreateQuoteTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
