<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="C1128" ignored="1" name="ChromeTest2" tests="2" failures="2" timestamp="27 Oct 2017 10:33:49 GMT" time="1.263" errors="0">
  <testcase name="loadconfig" time="0.232" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.PropertiesHandleException" message="ERROR IN RETRIVING DATA FROM -- RootFolder">
      <![CDATA[com.selenium.exception.PropertiesHandleException: ERROR IN RETRIVING DATA FROM -- RootFolder
	at com.selenium.Configuration.PropertiesHandle.RdmsValue(PropertiesHandle.java:117)
	at com.selenium.Configuration.PropertiesHandle.ScreenshotPath(PropertiesHandle.java:191)
	at com.selenium.Configuration.PropertiesHandle.WriteProperty(PropertiesHandle.java:80)
	at com.selenium.Configuration.PropertiesHandle.<init>(PropertiesHandle.java:50)
	at com.selenium.Test.UIMainscript.loadconfig(UIMainscript.java:69)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.selenium.exception.DatabaseException: PROBLEM WITH RESULT-SET OBTAINED FROM DB
	at com.selenium.SupportingClasses.DatabaseOperation.GetDataObjects(DatabaseOperation.java:118)
	at com.selenium.Configuration.PropertiesHandle.RdmsValue(PropertiesHandle.java:107)
	... 24 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 5 ms ago.
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2871)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3414)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2536)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1383)
	at com.selenium.SupportingClasses.DatabaseOperation.GetDataObjects(DatabaseOperation.java:99)
	... 25 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:113)
	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:160)
	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:188)
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2428)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2882)
	... 33 more
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loadconfig -->
  <testcase name="Login" time="1.001" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.selenium.Test.UIMainscript.Login(UIMainscript.java:94)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase name="UITest" time="0.0" classname="com.selenium.Test.UIMainscript">
    <ignored/>
  </testcase> <!-- UITest -->
</testsuite> <!-- ChromeTest2 -->
