<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="C1128" ignored="0" name="ChromeTest1" tests="209" failures="63" timestamp="11 Oct 2017 09:11:52 GMT" time="98.537" errors="0">
  <testcase name="Login" time="33.356" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.016" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.025" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.037" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.041" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.046" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.013" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.026" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.058" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.065" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.065" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.088" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.038" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.035" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.026" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.069" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.082" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.082" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.142" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.012" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.016" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.033" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.048" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.07" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.081" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.089" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.015" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.118" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.037" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.034" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.05" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.024" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.067" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.067" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.03" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.031" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.02" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.023" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.034" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.045" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.017" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '47' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.053" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.058" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.05" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.045" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '46-Test_data_46' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.024" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.034" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.042" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.063" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.014" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.014" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.033" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.045" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.007" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.026" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.028" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.027" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.042" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.02" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '63' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.014" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.035" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.018" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.042" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.039" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.045" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.014" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.007" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.031" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.035" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.021" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.025" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.012" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '74' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.022" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '74' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.013" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.014" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.024" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.033" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.029" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.02" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.035" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.01" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.017" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.053" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.007" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.039" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.021" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '87' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.043" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.021" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.031" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.011" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.019" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.028" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.016" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.042" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.057" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.039" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.026" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.065" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.012" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '105' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.021" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.033" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.042" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.032" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.053" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.053" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.021" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.017" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.038" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.031" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.024" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.054" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.06" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.057" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.059" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.058" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.005" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '123' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.043" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.007" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '125' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.013" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.079" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.044" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.027" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.037" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.013" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.012" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.014" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.033" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.074" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.014" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.025" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.028" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.016" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.038" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.037" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.025" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.037" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.032" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.014" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.038" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.026" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.037" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.025" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '144' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.03" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.04" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.019" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.038" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.022" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.011" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.045" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.061" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.031" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.052" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.024" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.059" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.041" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.038" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.049" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.039" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.014" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '165' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.049" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.024" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.04" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.05" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.044" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.049" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.01" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.019" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.03" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.031" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.044" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.009" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.042" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.029" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.002" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.026" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.013" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.037" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.007" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.009" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.003" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.022" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.014" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.034" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.013" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.003" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.023" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.035" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.066" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.048" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.013" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.025" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.029" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.039" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.046" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.01" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.022" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.021" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.008" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '203' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.03" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '196-Test_data_196' for key 'PRIMARY'
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2019)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.02" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.021" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.046" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.039" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.021" classname="com.selenium.Test.UIMainscript">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.mysql.jdbc.UpdatableResultSet.syncUpdate(UpdatableResultSet.java:1499)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2445)
	at com.mysql.jdbc.UpdatableResultSet.updateString(UpdatableResultSet.java:2483)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:136)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.012" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.018" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="0.016" classname="com.selenium.Test.UIMainscript">
    <failure type="com.selenium.exception.DatabaseException" message="PROBLEM WITH UPDATE ROW IN DB">
      <![CDATA[com.selenium.exception.DatabaseException: PROBLEM WITH UPDATE ROW IN DB
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:147)
	at com.selenium.Test.UIMainscript.UITest(UIMainscript.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2176)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1993)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1937)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1922)
	at com.mysql.jdbc.UpdatableResultSet.updateRow(UpdatableResultSet.java:2363)
	at com.selenium.SupportingClasses.DatabaseOperation.UpdateRow(DatabaseOperation.java:138)
	... 15 more
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- UITest -->
  <testcase name="UITest" time="0.016" classname="com.selenium.Test.UIMainscript"/>
  <testcase name="UITest" time="61.521" classname="com.selenium.Test.UIMainscript"/>
</testsuite> <!-- ChromeTest1 -->
